name: truth_or_dare_spinner
version: 1.0.0+1
description: Offline Flutter game for friends - Truth or Dare Spinner
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  flutter_animate: ^4.3.0
  flutter_spinkit: ^5.2.0
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true 